const homeRoutes = require("./home.route")
const productsRoutes = require("./products.route")
const searchRouters = require("./search.route")
const categoryMiddleware = require('../../middlewares/client/category.middleware')
const cartMiddleware = require('../../middlewares/client/cart.middleware')
const cartRouters = require("./cart.route")
const checkoutRoute = require("./checkout.route")
const userRoute = require("./user.route")
const chatRoute = require('./chat.route')
const userMiddleware = require('../../middlewares/client/user.middleware')
module.exports = (app) => {
    app.use(categoryMiddleware.category)
    app.use(cartMiddleware.cardID)
    app.use(userMiddleware.inforUser)
    app.use("/home", homeRoutes)
    app.use("/products", productsRoutes)
    app.use("/search", searchRouters)
    app.use("/cart", cartRouters)
    app.use("/checkout", checkoutRoute)
    app.use("/user", userRoute)
    app.use("/chat", chatRoute)
}