const express = require("express")
const router = express.Router()
const controller = require("../../controllers/client/user.controller.js")
const userValidate = require('../../validates/client/user.validate.js')
const authMiddleware = require('../../middlewares/client/auth.middlewear')
router.get('/register', controller.register)
router.post('/register', userValidate.resgisterPost, controller.registerPost)
router.get('/login', controller.login)
router.post('/login', controller.loginPost)
router.get('/log-out', controller.logOut)
router.get('/password/forget', controller.forget)
router.post('/password/forget', controller.forgetPost)
router.get('/password/otp', controller.otp)
router.post('/password/otp', controller.otpPost)
router.get('/info', authMiddleware.requireAuth, controller.info)
module.exports = router